
update: remove_desktop_file_from_apps copy_desktop_file_to_apps
	$(info ╦ ╦┌─┐┌┬┐┌─┐┌┬┐┌─┐  ╦  ┌─┐┬ ┬┌┐┌┌─┐┬ ┬┌─┐┬─┐)
	$(info ║ ║├─┘ ││├─┤ │ ├┤   ║  ├─┤│ │││││  ├─┤├┤ ├┬┘)
	$(info ╚═╝┴  ─┴┘┴ ┴ ┴ └─┘  ╩═╝┴ ┴└─┘┘└┘└─┘┴ ┴└─┘┴└─)

add: copy_desktop_file_to_apps
	$(info ╔═╗┌┬┐┌┬┐  ╦  ┌─┐┬ ┬┌┐┌┌─┐┬ ┬┌─┐┬─┐)
	$(info ╠═╣ ││ ││  ║  ├─┤│ │││││  ├─┤├┤ ├┬┘)
	$(info ╩ ╩─┴┘─┴┘  ╩═╝┴ ┴└─┘┘└┘└─┘┴ ┴└─┘┴└─)

remove: remove_desktop_file_from_apps
	$(info ╦═╗┌─┐┌┬┐┌─┐┬  ┬┌─┐  ╦  ┌─┐┬ ┬┌┐┌┌─┐┬ ┬┌─┐┬─┐)
	$(info ╠╦╝├┤ ││││ │└┐┌┘├┤   ║  ├─┤│ │││││  ├─┤├┤ ├┬┘)
	$(info ╩╚═└─┘┴ ┴└─┘ └┘ └─┘  ╩═╝┴ ┴└─┘┘└┘└─┘┴ ┴└─┘┴└─)

copy_desktop_file_to_apps:
	cd /home/dylan/Desktop/GITHUBS/MinecraftLauncher/launcher && \
	sudo cp MinecraftLau.desktop /usr/share/applications/

remove_desktop_file_from_apps: 
	sudo rm /usr/share/applications/MinecraftLau.desktop